version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_db}
    ports:
      - "5432:5432"
    container_name: retail_db
    restart: always
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d {POSTGRES_db}
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - my_todolist:/var/lib/postgresql/data/

  volumes:
    my_todolist:
